name: flutter_wordle
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  equatable: ^2.0.5
  dio: ^5.1.2
  freezed: ^2.1.1
  json_serializable: ^6.5.1
  json_annotation: ^4.7.0
  liquid_pull_to_refresh: ^3.0.1
  riverpod: ^2.3.6
  hooks_riverpod: ^2.1.1
  flutter_vibrate: ^1.3.0
  google_fonts: ^5.1.0
  flex_color_scheme: ^7.1.2
  flutter_inset_box_shadow: ^1.0.8
  go_router: ^9.0.0
  lottie: ^2.4.0
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/google_fonts/
    - assets/lottie/



  fonts:

    - family: RobotoCondensed
      fonts:
        - asset: assets/google_fonts/RobotoCondensed-Bold.ttf
          weight: 700
        - asset: assets/google_fonts/RobotoCondensed-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/google_fonts/RobotoCondensed-Regular.ttf
          weight: 400
        - asset: assets/google_fonts/RobotoCondensed-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/google_fonts/RobotoCondensed-Light.ttf
          weight: 300
        - asset: assets/google_fonts/RobotoCondensed-LightItalic.ttf
          weight: 300
          style: italic
